Updated national focuses localisation (Russian)
Wolferos/Hearts-of-Iron-IV-The-Great-War pull request #561
Opened 2024-02-09 14:35 UTC by kremastra

Correction of Russian localisation according to literary norms of the Russian language + partial translation of the missing localisation from English.

2024-02-11 16:49 UTC, dungeon-slave requested changes
Просмотрел пока что переводы только до # [AUSTRIA-HUNGARIAN EMPIRE] Naval Effort в первом доке

Потом продолжу, предлагаю не мерджить эти изменения, пока не закончим со всеми косяками, как будет время сам сяду их исправлять, но если ты свои замечания оставишь или поправишь часть из них - буду только благодарен. На исправленные ставь resolved пж

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_equipment_effort_3_desc:0 "К нам прищло письмо от квартирмейстеров с требованием оснастить армию большим количеством винтовок, приспособленных для траншейной войны, а если говорить прямо, то
ошибка в слове пришло

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_special_forces_desc:0 "Несмотря на жестокость химических атак, именно они помогли выделить отряды, которые отличаются невероятной реакцией, превосходящей все остальные войска. Эти отряды мог
мне кажется, что в этих местах: ", чем у обычной пехоты" и "так же быстро, как старая добрая кавалерия..." нужны запятые

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_army_motorization_focus_desc:0 "Великие умы нашего генштаба, а может просто люди, которым уже вдоволь надоела эта позиционная война, предложили нам начать массовое производство машин для наш
иными словами стоит обернуть в запятые, тк это вводное словосочетание

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_doctrine_effort_3_desc:0 "До сих пор мы игнорировали один из самых ключевых элементов военных действий — Логистику. Помимо заботы о ведении самого боя, нам нужно обеспечить своевременные пос
логистику лучше с маленькой

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_equipment_effort_desc:0 "Генералы старой гвардии не являются единственной причиной, по которой наши войска застряли в прошлом веке. Наши квартирмейстеры подвержены коррупции и вообще не хотя
мне кажется, тут лучше СЛИШКОМ нормально написать, тк в контексте данного описания не очень понятно на что это намек и зачем оно капсом выделено

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_equipment_effort_2_desc:0 "Новые квартирмейстеры помимо нового вооружения запросили у нас и новые орудия поддержки пехоты. Обсуждения новой модели армии привели к появлению идей о легких пул
"помимо нового вооружения" стоит в запятые обернуть, а в "до тех пор", наоборот, в начале запятую убрать

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_equipment_effort_3_desc:0 "К нам прищло письмо от квартирмейстеров с требованием оснастить армию большим количеством винтовок, приспособленных для траншейной войны, а если говорить прямо, то
плюс в слове должны ниже

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_armor_effort_1_desc:0 "Наши предшествующие усилия не пропали даром! Конструкторы и инженеры артиллерии и автомашин предложили нам новый вид техники — тяжелобронированный трактор с орудием пр
"наконец" стоит обернуть в запятые, еще думаю насчет "однако", чтобы после него запятую въебать, но тут под вопросом пока

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_armor_effort_2_desc:0 "Наши эксперименты с бронетехникой показывают все более многообещающие успехи! Однако, мы все равно недовольны существующими образцами. Инженеры предлагают нам множеств
перед "таких как" стоит добавить запятую. А вообще, я думаю, здесь проще будет нахуй убрать это, оно так проще читаться станет + повторение уберет

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_armor_effort_2_desc:0 "Наши эксперименты с бронетехникой показывают все более многообещающие успехи! Однако, мы все равно недовольны существующими образцами. Инженеры предлагают нам множеств
"особые" в данном контексте, наверное, стоит заменить на "отдельные".

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_fighter_focus_desc:0 "Ценность истребителя нельзя даже оспаривать. Сосредоточив наши усилия на разработке и использовании этого типа самолётов, наша нация сможет заполонить небо воздушной те
ошибка в слове яйца + я бы подумал насчет "Бомбардировщиков" с маленькой буквы

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_fighter_focus_desc:0 "Ценность истребителя нельзя даже оспаривать. Сосредоточив наши усилия на разработке и использовании этого типа самолётов, наша нация сможет заполонить небо воздушной те
после "может" в конце нужна запятая

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_bomber_focus_desc:0 "Бомбардировщик — это простая и при этом крайне практичная техника. Обеспечив все ресурсы на развитие этого вида самолётов, мы гарантируем, что ВВС станут прекрасным инст
Тут, я думаю, лучше заменить "Обеспечив" на "Предоставив" или перефразировать: Обеспечив развитие этого вида самолётов всеми ресурсами, мы гарантируем и т.д.

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_airship_focus_desc:0 "Цеппелин — дирижабли жёсткой системы, строившиеся графом Цеппелином и немецкой фирмой «Люфтшиффбау Цеппелин ГмбХ». Названы по имени их изобретателя и создателя Фердинан
"не совсем точно" явно стоит убрать

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_aviation_effort_4:0 "Развитие авиации III"
почему такое большое пространство между заголовком и текстом?

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_aviation_effort_4_desc:0 "Наши воздушные силы созданные так недавно, уже стали неотъемлимой частью наших вооруженных сил. Все растущее взаимодействие между войсками приводит к появлению множ
перед "созданные так недавно" нужна запятая

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_pilotformation_1_desc:0 "В данный момент самолёты летают поодиночке и на большом расстоянии друг от друга, периодически вступая в дуэль с вражеской техникой. Однако в небе появляется все бол
физики?

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_pilotformation_2_desc:0 "Новые боевые порядки вызвали море шума в военной авиации. Однако еще нужно еще убедиться, что летчики будут придерживаться их и в бою. Вдохновив асов на создание спе
Во втором предложении лишнее ещё

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_aircraftprod_1_desc:0 "Хоть наши конструкторы собирают приличное количество самолётов, однако пора уже подключить к этому делу наши заводы. Начав массовое производство самолётов, мы не тольк
"Хоть наши конструкторы собирают приличное количество самолётов, однако пора уже подключить к этому делу наши заводы. Начав массовое производство самолётов, мы не только заполним наше небо дружественной авиацией, но что более важно, лишим врага такого же потенциального преимущества над нами. И в конце концов, кто знает, может заводские инженеры предложат нам интересные улучшения для нашей техники..." стоит заменить на 

"Хоть наши конструкторы и собирают приличное количество самолётов, однако пора уже подключить к этому делу заводы. Начав массовое производство самолётов, мы не только заполним наше небо дружественной авиацией, но, что более важно, лишим врага такого же потенциального преимущества над нами. И, в конце концов, кто знает, может заводские инженеры предложат нам интересные улучшения для нашей техники..."

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_aircraftprod_2_desc:0 "В то время как основная часть самолётов производится на заводах по производству техники, у нас появились особые предприятия, занимающиеся исключительно производством с
- [ ] после "В то время" запятую
- [ ] "занимающиеся исключительно производством самолётов" заменить на "занимающиеся исключительно самолётами"
- [ ] в части "основная часть самолётов производится" заменить "производится" на "собирается", учитывая верхнее исправление, мы избавимся от тавтологии в этом описании
- [ ] в "эти производства определённо помогут" заменить "производства" на "предприятия"
- [ ] в "помогут нам в создании новой техники" заменить "новой техники" на "новых самолётов" 
- [ ] в "ускорении производства уже существующих" заменить "производства" на "сборки" 
- [ ] убрать enter после "уже" (? : судя по форматированию, он там есть)

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_air_innovation_desc:0 "Недавние открытия в воздушной войне как в теории, так и в практике, позволяют заявить о начале золотого века в развитии авиации. От простого механика до асов — все пре
после "Возможно" в конце запятая

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_navalair_desc:0 "Один из наших многообещающих офицеров сегодня показал нам наработки по проекту, над которым он секретно работал. Палубный самолёт взлетел со стоящего корабля, сбросил бомбу
не очень понимаю зачем тут запятая перед "и затем приземлился обратно на площадку"

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_construction_effort_3_desc:0 "Расширение нашей гражданской промышленности почти закончено, однако у нас есть еще один замысел. Мы можем продать компаниям некоторые пригородные земли, при усл
- [ ] заменить "они будут использовать её" на "они будут использовать их"
- [ ] "еще" заменить на "ещё"
- [ ] в "у нас практически не осталось способов для роста производства" заменить "не осталось" на "не останется"

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_production_effort_2_desc:0 "Автомобильный концерн, до этого прозводящий для нас армейскую технику, теперь хочет создать отдельный завод по производству военной продукции, чтобы за счет освоб
- [ ] В начале описания "прозводящий" заменить на "производящий"
- [ ] В предпоследней строчке "заинтресованы" заменить на "заинтересованы"
- [ ] Последнее предложение: "обернется" на "обернётся"
- [ ] Третье предложение описания: "счет" на "счёт"

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_production_effort_3_desc:0 "Один из авиационных конструкторов попросил нас о помощи в создании нового завода по производству его авиатехники для наших ВВС. Хотя его модели не были протестиро
в последнем предложении "наши военный промышленный потенциал" лучше заменить на "наш военно-промышленный потенциал"

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_dockyard_effort_1_desc:0 "Выкупив неиспользуемые прибрежные земли и расширив нашу существующую инфраструктуру, мы сможем увеличить наши производтсвенные сощности по выпуску кораблей."
"производтсвенные сощности" заменить на "производственные мощности"

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_airfield_expansion_1_desc:0 "Для постройки аэродромов нужен лишь открытый участок земли, находящийся рядом с дорожной сетью. Создание самих полос и инфраструктуры это конечно, серьезная рабо
перед "конечно" в предпоследней строчке добавить запятую

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_airfield_expansion_2_desc:0 "Некоторые гражданские посадочные полосы заброшены,выкупив и восстановив их, мы легко сможем использовать их для наших целей."
пробел перед "выкупив"

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_airfield_expansion_3_desc:0 "Построив полноценные аэродромы у больших городов, мы сможем создать сеть легко снабжаемых баз для наших самолётов, что позволит нам существенно лучше оборонять с
заменить "существенного" на "намного" или вообще убрать

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_infrastructure_effort_desc:0 "По мере роста промышленности, частный сектор все чаще требует от нас инвестиций в инфраструктуру, что поможет росту экономики. Но если мы начнем заниматься этим
- [ ] "что поможет росту экономики" заменить на "что необходимо для роста экономики"
- [ ] обернуть "может" в последней строке запятыми

2024-02-11 16:49 UTC, dungeon-slave commented on mod/thegreatwar/localisation/ww1_nf_auh_l_russian.yml
> + AUH_ww1_infrastructure_effort_2_desc:0 "Хотя у нас постоянно растет количество заводов, верфей и аэродромов, у нас еще есть возможности для новых вложений. Следующим логичным шагом станет развитие с
- [ ] "Хотя у нас постоянно растет количество заводов, верфей и аэродромов, у нас еще есть возможности для новых вложений." заменить на "Хоть у нас и постоянно растёт количество заводов, верфей и аэродромов, ещё есть возможности для новых вложений."

2024-02-11 16:56 UTC, dungeon-slave commented
> Correction of Russian localisation according to literary norms of the Russian language + partial translation of the missing localisation from English.

suggest not to merge this before check and making corrections

2024-02-11 17:29 UTC, kremastra commented
> Просмотрел пока что переводы только до # [AUSTRIA-HUNGARIAN EMPIRE] Naval Effort в первом доке
> 
> Потом продолжу, предлагаю не мерджить эти изменения, пока не закончим со всеми косяками, как будет время, сам сяду их исправлять, но если ты свои замечания оставишь или поправишь часть из моих - буду только благодарен. На исправленные ставь resolved пж

Смотри, тут ещё такая весчь: эти неточности типа "прищло" и "Логистики" - они в фокусах практически всех крупных стран по причине копипасты. Если что-то мне попадалось на глаза - я исправлял, но так, чтобы составить список всех замечаний и проверять по нему все страны по очереди - такого не было. Возможно, такой список стоит и создать...

2024-02-13 08:14 UTC, dungeon-slave commented
> > Просмотрел пока что переводы только до # [AUSTRIA-HUNGARIAN EMPIRE] Naval Effort в первом доке
> > 
> > Потом продолжу, предлагаю не мерджить эти изменения, пока не закончим со всеми косяками, как будет время, сам сяду их исправлять, но если ты свои замечания оставишь или поправишь часть из моих - буду только благодарен. На исправленные ставь resolved пж
> 
> Смотри, тут ещё такая весчь: эти неточности типа "прищло" и "Логистики" - они в фокусах практически всех крупных стран по причине копипасты. Если что-то мне попадалось на глаза - я исправлял, но так, чтобы составить список всех замечаний и проверять по нему все страны по очереди - такого не было. Возможно, такой список стоит и создать...

Понимаю, но я подумал, раз уж ты эти файлы трогать решился, то лучше тогда все более-менее видимые косяки позакрываать. А что по копипасте — да, это проблема. Тут вообще, по-хорошему, было бы одинаковые описания все в отдельные файлики вынести, чтобы хуйней не заниматься каждый раз.

Ладно, го подумаем как лучше поступить, может реально будет на данном этапе достаточно накидать какой-нибудь список косяков таких общих в те же таски на GitHub, если будем так делать, то я нормально проект склонирую и поищу все места, где оно повторяется и составлю полный список инфы и потом уже будем думать как поступить — выносить или везде заменять.

Что думаешь?

2024-02-13 09:24 UTC, kremastra commented
> > > Просмотрел пока что переводы только до # [AUSTRIA-HUNGARIAN EMPIRE] Naval Effort в первом доке
> > > Потом продолжу, предлагаю не мерджить эти изменения, пока не закончим со всеми косяками, как будет время, сам сяду их исправлять, но если ты свои замечания оставишь или поправишь часть из моих - буду только благодарен. На исправленные ставь resolved пж
> > 
> > 
> > Смотри, тут ещё такая весчь: эти неточности типа "прищло" и "Логистики" - они в фокусах практически всех крупных стран по причине копипасты. Если что-то мне попадалось на глаза - я исправлял, но так, чтобы составить список всех замечаний и проверять по нему все страны по очереди - такого не было. Возможно, такой список стоит и создать...
> 
> Понимаю, но я подумал, раз уж ты эти файлы трогать решился, то лучше тогда все более-менее видимые косяки позакрываать. А что по копипасте — да, это проблема. Тут вообще, по-хорошему, было бы одинаковые описания все в отдельные файлики вынести, чтобы хуйней не заниматься каждый раз.
> 
> Ладно, го подумаем как лучше поступить, может реально будет на данном этапе достаточно накидать какой-нибудь список косяков таких общих в те же таски на GitHub, если будем так делать, то я нормально проект склонирую и поищу все места, где оно повторяется и составлю полный список инфы и потом уже будем думать как поступить — выносить или везде заменять.
> 
> Что думаешь?

Я не против. Но этим нужно прямо вплотную заниматься. Лично я уже немного пожалел, что такой размах взял, ведь изначально собирался тупо недостающие фокусы локализовать, а кончилось всё построчной вычиткой целых файлов. Так что если не горит, я бы отложил на время эту тему. Тем более, я тут занялся потихоньку исправлением исторических неточностей, и как-то с локализацией это мешать особо не улыбается. Но на список мб время найду, посмотрим...

2024-02-13 15:25 UTC, dungeon-slave commented
Согласен, я ж и говорю, что сейчас не горит всё это исправлять, но накинуть хотя бы список по уже готовым и таску неплохо бы. Я хз, получится ли у меня на неделе этим заняться, но на выходных точно сяду поторогаю

2024-02-13 15:25 UTC, dungeon-slave commented
> > > > Просмотрел пока что переводы только до # [AUSTRIA-HUNGARIAN EMPIRE] Naval Effort в первом доке
> > > > Потом продолжу, предлагаю не мерджить эти изменения, пока не закончим со всеми косяками, как будет время, сам сяду их исправлять, но если ты свои замечания оставишь или поправишь часть из моих - буду только благодарен. На исправленные ставь resolved пж
> > > 
> > > 
> > > Смотри, тут ещё такая весчь: эти неточности типа "прищло" и "Логистики" - они в фокусах практически всех крупных стран по причине копипасты. Если что-то мне попадалось на глаза - я исправлял, но так, чтобы составить список всех замечаний и проверять по нему все страны по очереди - такого не было. Возможно, такой список стоит и создать...
> > 
> > Понимаю, но я подумал, раз уж ты эти файлы трогать решился, то лучше тогда все более-менее видимые косяки позакрываать. А что по копипасте — да, это проблема. Тут вообще, по-хорошему, было бы одинаковые описания все в отдельные файлики вынести, чтобы хуйней не заниматься каждый раз.
> > 
> > Ладно, го подумаем как лучше поступить, может реально будет на данном этапе достаточно накидать какой-нибудь список косяков таких общих в те же таски на GitHub, если будем так делать, то я нормально проект склонирую и поищу все места, где оно повторяется и составлю полный список инфы и потом уже будем думать как поступить — выносить или везде заменять.
> > 
> > Что думаешь?
> 
> Я не против. Но этим нужно прямо вплотную заниматься. Лично я уже немного пожалел, что такой размах взял, ведь изначально собирался тупо недостающие фокусы локализовать, а кончилось всё построчной вычиткой целых файлов. Так что если не горит, я бы отложил на время эту тему. Тем более, я тут занялся потихоньку исправлением исторических неточностей, и как-то с локализацией это мешать особо не улыбается. Но на список мб время найду, посмотрим...

Согласен, я ж и говорю, что сейчас не горит всё это исправлять, но накинуть хотя бы список по уже готовым и таску неплохо бы. Я хз, получится ли у меня на неделе этим заняться, но на выходных точно сяду поторогаю

2024-02-20 10:20 UTC, merged